### ISSUE TITLE
How does one create a docElement?

### ISSUE THREAD

**Issue by mbleigh** [unified-doc/unified-doc-dom#2]
In the docs, it describes a `docElement` as a rendered container coming from a `unified-doc`. However, from what I can tell the VFile created by `doc.compile()` is just the stringified doc contents without a common "root".

Assuming I create a doc using something like:

```js
const doc = Doc({content: "# Some Markdown\n\nContent goes here.", filename: "source.md"});
```

How do I then put that into my HTML document in such a way that it can be recognized by `unified-doc-dom` utility methods?

**Comment by chrisrzhou** [comment]
Hi @mbleigh, that's for you to insert however you like! Although this prompts creating a utility in `unified-doc-dom` that could do this in the future e.g.

```ts
function createDocElement(doc: DocInstance): HTMLDivElement {}
```

In the meantime, you can do this yourself using vanilla JS or framework-specific ways to do this.  The general idea is to set the `doc.compile()` contents under a HTML div element.

Here's some examples

### React
```js
function MyDoc() {
  const doc = Doc({ ... });

  const docRef = useRef(); // you can reference docRef.current to get the HTML element and use this with `unified-doc-dom` utilities.
  
  return (
    <div ref={docRef}>
      {doc.compile()}
    </div>
  );
}
```

### JS
```js
const doc = Doc({ ... });

const docElement = document.createElement('div');
// vanilla JS to insert doc.compile() under docElement, however it makes sense.

function myMethod() {
  // work with docElement and unified-doc-dom methods.
}
```

**Comment by mbleigh** [comment]
Got it. It seems the problem is that this library (or more likely the underlying `rangy` library) isn't compatible with Shadow DOM selection, so it was throwing a "no common ancestor" error. Switching to Light DOM got things working.

**Comment by chrisrzhou** [comment]
Nice, it's not explicit in the project readme, but this library is intended to work with basic DOM.  There's a chance Shadow/Light/abstract DOM implementations don't fully support some DOM APIs.

I haven't had time to flesh this project out more, but thanks for the feedback and checking it out!
